font=JetBrainsMono Nerd Font:size=12

[colors]
#background=161e0d
background=000000
foreground=c4c6c2
regular0=161e0d
regular1=6B7B89
regular2=AE6389
regular3=D86D91
regular4=A69D9A
regular5=D4A0A5
regular6=D2C0BB
regular7=c4c6c2
bright0=67705c
bright1=6B7B89
bright2=AE6389
bright3=D86D91
bright4=A69D9A
bright5=D4A0A5
bright6=D2C0BB
bright7=c4c6c2
alpha=0.8
