--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kevin/Pictures/fern.png"

-- Special
background="#000000"
foreground="#ccc6d0"
cursor="#ccc6d0"

-- Colors
color0="#000000"
color1="#B85E9C"
color2="#93758F"
color3="#7484A1"
color4="#AC989D"
color5="#DCADA3"
color6="#D9C9AE"
color7="#ccc6d0"
color8="#796c85"
color9="#B85E9C"
color10="#93758F"
color11="#7484A1"
color12="#AC989D"
color13="#DCADA3"
color14="#D9C9AE"
color15="#ccc6d0"
