[colors]
background = '#0000008e'
black = '#000000'
blue = '#B85E9C'
cursor = '#ccc6d0'
cyan = '#93758F'
foreground = '#ccc6d0'
green = '#7484A1'
magenta = '#AC989D'
red = '#DCADA3'
tabs = '#ccc6d0'
tabs-active = '#D9C9AE'
white = '#ccc6d0'
yellow = '#ccc6d0'
dim-black = '#0000008e'
dim-blue = '#B85E9C8e'
dim-cyan = '#93758F8e'
dim-foreground = '#ccc6d08e'
dim-green = '#7484A18e'
dim-magenta = '#AC989D8e'
dim-red = '#DCADA38e'
dim-white = '#D9C9AE8e'
dim-yellow = '#ccc6d08e'
light-black = '#B85E9C'
light-blue = '#93758F'
light-cyan = '#7484A1'
light-foreground = '#AC989D'
light-green = '#DCADA3'
light-magenta = '#D9C9AE'
light-red = '#ccc6d0'
light-white = '#B85E9C'
light-yellow = '#93758F'
