[colors.primary]
background = "#000000"
foreground = "#ccc6d0"

[colors.cursor]
text = "#000000"
cursor = "#ccc6d0"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ccc6d0"

[colors.search.matches]
foreground = "#000000"
background = "#ccc6d0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#796c85"
background = "#ccc6d0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#B85E9C"
green = "#93758F"
yellow = "#7484A1"
blue = "#AC989D"
magenta = "#DCADA3"
cyan = "#D9C9AE"
white = "#ccc6d0"

[colors.bright]
black = "#796c85"
red = "#B85E9C"
green = "#93758F"
yellow = "#7484A1"
blue = "#AC989D"
magenta = "#DCADA3"
cyan = "#D9C9AE"
white = "#ccc6d0"

[colors.dim]
black = "#ccc6d0"
red = "#B85E9C"
green = "#DCADA3"
yellow = "#7484A1"
blue = "#AC989D"
magenta = "#93758F"
cyan = "#D9C9AE"
white = "#796c85"

