# Shell variables
# Generated by 'wal'
wallpaper="/home/kevin/Pictures/fern.png"

# Special
background='#000000'
foreground='#ccc6d0'
cursor='#ccc6d0'

# Colors
color0='#000000'
color1='#B85E9C'
color2='#93758F'
color3='#7484A1'
color4='#AC989D'
color5='#DCADA3'
color6='#D9C9AE'
color7='#ccc6d0'
color8='#796c85'
color9='#B85E9C'
color10='#93758F'
color11='#7484A1'
color12='#AC989D'
color13='#DCADA3'
color14='#D9C9AE'
color15='#ccc6d0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
