# pywal theme for ghostty

background = 000000
foreground = ccc6d0
cursor-color = ccc6d0
selection-background = ccc6d0
selection-foreground = 000000

palette = 0=#000000
palette = 1=#B85E9C
palette = 2=#93758F
palette = 3=#7484A1
palette = 4=#AC989D
palette = 5=#DCADA3
palette = 6=#D9C9AE
palette = 7=#ccc6d0
palette = 8=#796c85
palette = 9=#B85E9C
palette = 10=#93758F
palette = 11=#7484A1
palette = 12=#AC989D
palette = 13=#DCADA3
palette = 14=#D9C9AE
palette = 15=#ccc6d0
