# Shell variables
# Generated by 'wal'
wallpaper="/home/kevin/Pictures/sakura.jpg"

# Special
background='#161e0d'
foreground='#c4c6c2'
cursor='#c4c6c2'

# Colors
color0='#161e0d'
color1='#6B7B89'
color2='#AE6389'
color3='#D86D91'
color4='#A69D9A'
color5='#D4A0A5'
color6='#D2C0BB'
color7='#c4c6c2'
color8='#67705c'
color9='#6B7B89'
color10='#AE6389'
color11='#D86D91'
color12='#A69D9A'
color13='#D4A0A5'
color14='#D2C0BB'
color15='#c4c6c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
