foreground         #c4c6c2
background         #161e0d
background_opacity 1.0
cursor             #c4c6c2

active_tab_foreground     #161e0d
active_tab_background     #c4c6c2
inactive_tab_foreground   #c4c6c2
inactive_tab_background   #161e0d

active_border_color   #c4c6c2
inactive_border_color #161e0d
bell_border_color     #6B7B89

color0       #161e0d
color8       #67705c
color1       #6B7B89
color9       #6B7B89
color2       #AE6389
color10      #AE6389
color3       #D86D91
color11      #D86D91
color4       #A69D9A
color12      #A69D9A
color5       #D4A0A5
color13      #D4A0A5
color6       #D2C0BB
color14      #D2C0BB
color7       #c4c6c2
color15      #c4c6c2
