--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kevin/Pictures/sakura.jpg"

-- Special
background="#161e0d"
foreground="#c4c6c2"
cursor="#c4c6c2"

-- Colors
color0="#161e0d"
color1="#6B7B89"
color2="#AE6389"
color3="#D86D91"
color4="#A69D9A"
color5="#D4A0A5"
color6="#D2C0BB"
color7="#c4c6c2"
color8="#67705c"
color9="#6B7B89"
color10="#AE6389"
color11="#D86D91"
color12="#A69D9A"
color13="#D4A0A5"
color14="#D2C0BB"
color15="#c4c6c2"
