[colors]
background = '#161e0d8e'
black = '#161e0d'
blue = '#6B7B89'
cursor = '#c4c6c2'
cyan = '#AE6389'
foreground = '#c4c6c2'
green = '#D86D91'
magenta = '#A69D9A'
red = '#D4A0A5'
tabs = '#c4c6c2'
tabs-active = '#D2C0BB'
white = '#c4c6c2'
yellow = '#c4c6c2'
dim-black = '#161e0d8e'
dim-blue = '#6B7B898e'
dim-cyan = '#AE63898e'
dim-foreground = '#c4c6c28e'
dim-green = '#D86D918e'
dim-magenta = '#A69D9A8e'
dim-red = '#D4A0A58e'
dim-white = '#D2C0BB8e'
dim-yellow = '#c4c6c28e'
light-black = '#6B7B89'
light-blue = '#AE6389'
light-cyan = '#D86D91'
light-foreground = '#A69D9A'
light-green = '#D4A0A5'
light-magenta = '#D2C0BB'
light-red = '#c4c6c2'
light-white = '#6B7B89'
light-yellow = '#AE6389'
